### ISSUE TITLE
`require': cannot load such file -- chef/resource/lwrp_base (LoadError)

### ISSUE THREAD

**Issue by aditaa** [realityforge/knife-cookbook-doc#17]
knife cookbook doc ./
/home/aditaa/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- chef/resource/lwrp_base (LoadError)
	from /home/aditaa/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/aditaa/.rvm/gems/ruby-1.9.3-p547/gems/knife-cookbook-doc-0.11.0/lib/knife_cookbook_doc/documenting_lwrp_base.rb:1:in `<top (required)>'
	from /home/aditaa/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/aditaa/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/aditaa/.rvm/gems/ruby-1.9.3-p547/gems/knife-cookbook-doc-0.11.0/lib/chef/knife/cookbook_doc.rb:10:in `block in <class:CookbookDoc>'
	from /home/aditaa/.rvm/gems/ruby-1.9.3-p547/gems/chef-0.10.8/lib/chef/knife.rb:202:in `call'
	from /home/aditaa/.rvm/gems/ruby-1.9.3-p547/gems/chef-0.10.8/lib/chef/knife.rb:202:in `load_deps'
	from /home/aditaa/.rvm/gems/ruby-1.9.3-p547/gems/chef-0.10.8/lib/chef/knife.rb:163:in `run'
	from /home/aditaa/.rvm/gems/ruby-1.9.3-p547/gems/chef-0.10.8/lib/chef/application/knife.rb:128:in `run'
	from /home/aditaa/.rvm/gems/ruby-1.9.3-p547/gems/chef-0.10.8/bin/knife:25:in `<top (required)>'
	from /home/aditaa/.rvm/gems/ruby-1.9.3-p547/bin/knife:23:in `load'
	from /home/aditaa/.rvm/gems/ruby-1.9.3-p547/bin/knife:23:in `<main>'
	from /home/aditaa/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `eval'
	from /home/aditaa/.rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `<main>'

**Comment by realityforge** [comment]
The recent version of this gem are not compatible with Chef 10. I believe knife-cookbook-doc 0.7.0 was the last version that was compatible with that version of chef.

**Comment by philoserf** [comment]
@realityforge We can list supported versions in the README. This will be easier once I have testing against multiple Chef versions up and running.

**Comment by realityforge** [comment]
That would be fantastic

**Comment by realityforge** [comment]
I think the resolution was to use an earlier version of knife-cookbook-doc with the old version of chef. Feel free to re-open if you find a later version of knife-cookbook-doc does not work with chef.

Thanks!
