### ISSUE TITLE
 lazy defaults are not rendered correct in LWRPs

### ISSUE THREAD

**Issue by fsimmend** [realityforge/knife-cookbook-doc#33]
an attribute 

``` ruby
attribute :java_home, :kind_of => String, :default => lazy { node['java']['home'] }
```

will be rendered to 

``` html
<code>#<Chef::DelayedEvaluator:0x007ffcdae07480@/PATH/resources/default.rb:155></code>.
```

**Comment by realityforge** [comment]
That's for the report. Do you have a good idea about how we could address this?

**Comment by fsimmend** [comment]
can't we do a classcheck and simply say its a derived default.

**Comment by realityforge** [comment]
Sounds very reasonable. If possible could you submit a pull request to do this ? )
